In [62]:
import numpy as np

<h1> Task 1</h1>

In [63]:
# creating the 1 D numy array

arr = np.array([i for i in range(1,11)])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
10
(10,)
int64


In [64]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
int64


In [65]:
arr2 = np.random.rand(3, 5, 3)
print(arr2)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)

[[[0.83414277 0.62475994 0.16497416]
  [0.91711671 0.49907566 0.00114251]
  [0.44285277 0.01424368 0.19334594]
  [0.9201019  0.99571678 0.59105537]
  [0.103724   0.62280312 0.89222391]]

 [[0.3929024  0.52673515 0.06568243]
  [0.09403669 0.47207766 0.60472805]
  [0.23678498 0.48674625 0.65640648]
  [0.77973471 0.43103649 0.56397532]
  [0.43619446 0.86800008 0.14186603]]

 [[0.72666772 0.04108744 0.849788  ]
  [0.64362341 0.98091731 0.30297696]
  [0.99446907 0.97329215 0.65302777]
  [0.13493167 0.04134552 0.27796189]
  [0.24562986 0.80495225 0.90921039]]]
45
(3, 5, 3)
float64


<h1> Task 2</h1>

In [66]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
for i in range(3):
    print(arr[i])

10
20
30


In [68]:
# Alternate element of an array

for i in range(0,arr.size,2):
    print(arr[i], end=" ")


10 30 50 70 90 

In [69]:
# reverse the array

arr1 = arr[::-1]
arr1

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

<h1> Task 3 : Mathematical Operation </h1>

In [70]:
import random

In [74]:
# NUMPY ARRAYS

arrA = [random.randint(1,20) for i in range(1,6)]
npArrA = np.array(arrA)
print(npArrA)

arrB = [random.randint(1,20) for i in range(1,6)]
npArrB = np.array(arrB)
print(npArrB)


[ 5 12 15 20 16]
[ 4 13 13 12 17]


In [72]:
# Mathematic Functions

# Addition
print('Addition')
print(npArrA + npArrB)

# Multiplication
print('Multiplication')
print(npArrA*npArrB)

# Division
print('Division')
print(npArrA/npArrB)

# Dot Product of two Arrays
print('Dot Product of two Arrays')
print(npArrA.dot(npArrB))

# Mean of Array A
print('Mean of Array A')
print(npArrA.mean())

# Median of array A
print('Median of array A')
print(np.median(npArrA))

# Standard Deviation of array A
print('Standard Deviation of array A')
print(np.std(npArrA))

# Variance of Array A
print('Variance of Array A')
print(np.var(npArrA))

# Maximum value of Array B and idx of a mx element
print('Maximum value of Array B and idx of a mx element')
print(np.max(npArrB))
print(np.argmax(npArrB))

# Minimum value of Array B and idx of a mn element
print('Minimum value of Array B and idx of a mn element')
print(np.min(npArrB))
print(np.argmin(npArrB))



Addition
[28 35 25 12 17]
Multiplication
[160 306 150  11  60]
Division
[2.5        0.94444444 0.66666667 0.09090909 0.41666667]
Dot Product of two Arrays
687
Mean of Array A
10.6
Median of array A
10.0
Standard Deviation of array A
7.116178749862878
Variance of Array A
50.64
Maximum value of Array B and idx of a mx element
18
1
Minimum value of Array B and idx of a mn element
8
0


<h1> Task 4 : </h1>

In [73]:
arr = np.arange(1,13)
print(arr)
print('2D Matrix')
print(arr.reshape(4,3))
print('3D Matrix')
print(arr.reshape(2,2,3))
print()
print('transposing the reshaped 2D array and display its shape. ')
print(arr.transpose())
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Matrix
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3D Matrix
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

transposing the reshaped 2D array and display its shape. 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


<h1>Task 5 :  Boolean Masking and Filtering </h1>

In [120]:
arr = np.array([random.randint(10,50) for i in range(1,15)])
print(f'Random array of 15 elements: {arr}')

arr2 = [i for i in arr if i > 25]
print(f'Found all elements greater than 25: {arr2}')

arr3 = [i*0 if i < 30 else i for i in arr]
print("Replacing all elements less than 30 with 0 :", end=" ")
for i in arr3:
    print(i, end=" ")
print()
c=0
for i in arr:
    if(i%5 == 0):
        c+=1
print(f'Count the number of elements divisible by 5 : {c}')

Random array of 15 elements: [39 16 15 38 34 11 18 34 39 20 13 23 28 10]
Found all elements greater than 25: [np.int64(39), np.int64(38), np.int64(34), np.int64(34), np.int64(39), np.int64(28)]
Replacing all elements less than 30 with 0 : 39 0 0 38 34 0 0 34 39 0 0 0 0 0 
Count the number of elements divisible by 5 : 3


<h1> Task 6: Working with built in Functions</h1>

In [110]:
arr = np.arange(0,1,.1)
print(f'Creating an array of 10 equally spaced values between 0 and 1 :{arr} ')

print(np.identity(4))

arr1 = np.random.randint(1,101, size=20)
srtdArr = np.sort(arr1)

# largest 5 elements 
largest = srtdArr[-5:]
print(f'Random array of size 20  {arr1}')
print(f'sorted array {srtdArr}')
print('5 largeest elemrnt :', largest)




Creating an array of 10 equally spaced values between 0 and 1 :[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random array of size 20  [ 52  40 100   8   3  25  10  93  85  46  62  42  95  12  26  20  11   6
  71  12]
sorted array [  3   6   8  10  11  12  12  20  25  26  40  42  46  52  62  71  85  93
  95 100]
5 largeest elemrnt : [ 71  85  93  95 100]


<h1> Generic </h1>

In [111]:
import time

In [112]:

# Generate two large random arrays of size (100, 100)
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Measure time
start_time = time.time()

# Perform matrix multiplication
result = np.dot(A, B)

# Try to compute determinant and inverse
try:
    determinant = np.linalg.det(result)
    inverse = np.linalg.inv(result)
    det_status = f"Determinant: {determinant}\nInverse computed successfully."
except np.linalg.LinAlgError as e:
    determinant = None
    inverse = None
    det_status = f"Matrix is singular or not invertible.\nError: {e}"

# Measure end time
end_time = time.time()
elapsed_time = end_time - start_time

# Output the results
print("Matrix multiplication completed.")
print(det_status)
print(f"Time taken for operations: {elapsed_time:.4f} seconds")


Matrix multiplication completed.
Determinant: -6.227499391488033e+50
Inverse computed successfully.
Time taken for operations: 0.0700 seconds
